service:
  name: altura-dos-famosos-api

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: "sa-east-1"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
  # iamRoleStatements:
  #   - ${file(iam/CelebrityTableIAM.yml):CelebrityTableIAM}

resources:
  Resources:
    CelebrityTable: ${file(resources/CelebrityTable.yml):CelebrityTable}

functions:
  putCelebrity:
    handler: src/handlers/putCelebrity.handler
    events:
      - http:
          method: POST
          path: /celebrity
  getCelebrities:
    handler: src/handlers/getCelebrities.handler
    events:
      - http:
          method: GET
          path: /celebrity

custom:
  CelebrityTable:
    name: !Ref CelebrityTable
    arn: !GetAtt CelebrityTable.Arn
